### ISSUE TITLE
请问，"6.使用授权码换取公众号的授权信息"里的authorization_code授权码，是在哪里获得？

### ISSUE THREAD

**Issue by klausgao** [liuxiaodong/weixin-service#1]
类库很好啊，卡在这里了！

请问，"6.使用授权码换取公众号的授权信息"里的authorization_code授权码，是在哪里获得？

**Comment by liuxiaodong** [comment]
这个参数微信会放在你的授权回调URI中。参数名称是 auth_code

https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318292&token=&lang=zh_CN
